### ISSUE TITLE
single gpu 관련

### ISSUE THREAD

**Issue by kimdanni** [POZAlabs/ComMU-code#12]
single gpu 에서 학습시에 train 부분에 ddp 를 제거하여 학습하였으나
무음이 생성되었고
generate 단에서 write 하는 부분을 살펴보니
![image](https://user-images.githubusercontent.com/68048205/204233439-497666f8-6174-4dbd-ab15-710a4316efe1.png)
해당 부분에서 position 이후에 note velocity, note on, note duration 이 출력되는 경우가 맨처음 이외에는 존재하지 않았고 그문제로 음악이 제대로 생성되지 않는 것이었습니다.
해당 코드 부분에 의미를 조금 설명해주실 수 있나요?
events 다음에 note velocity, note on, note duration이 차례대로 나와야지만 temp_notes 에 append 가 가능한 이유가 궁금합니다

**Comment by hyeonch** [comment]
우선 저희가 실험을 진행한 환경에서, 학습이 잘 되었을 경우 해당 이슈가 발생하는 일이 드물어 해당 리서치 코드에서 별다른 validation을 적용하지는 않은 상태입니다.
질문주신 내용과 PR을 살펴보았고, 단순히 DDP 모듈을 제거하는 것 뿐만 아니라 train 과정에서 dataset 배열이 broadcasting을 위해 batch chunk에 따라 contiguous 함수에 의해 배치되었기 때문에 dataset iteration 시 배열 또한 살펴보셔야 할 것 같습니다.
DDP를 사용하지 않으실거면 distributed.launch를 사용하실 필요도 없을 것으로 보입니다.
PR은 close하겠습니다.
감사합니다.

**Comment by kimdanni** [comment]
답변해주셔서 감사합니다! 살펴보도록 하겠습니다

**Comment by hyeonch** [comment]
@kimdanni 넵 감사합니다. 아직 conference 진행중이고, 현재 제공되는 코드가 지금 당장은 연구자 혹은 관심있는 분들을 위해 서비스 되는 느낌의 코드라기보다는 논문에서 활용된 환경속에서 실험내용이 얼마나 재현성있는지를 보여줄 수 있는 supplementary로서 생각해주셔야 할 것 같습니다. 다만 내년에 어느정도 dataset을 확장함과 동시에 실제 내부 서비스에 적용중인 코드를 기반으로 프로젝트의 리팩터링도 고려하고 있으니, 지속적으로 관심 가져주시면 감사드리겠습니다.
