### ISSUE TITLE
error in teacher forcing

### ISSUE THREAD

**Issue by nicsor** [POZAlabs/ComMU-code#4]
Is the current dataset ok to train the model so that we could run the example?
The csv has 3995 references, while the archive contains 11000 entries.

After training, based on that, the generate method does not work. For the next token in the sequence it generates 'generation_length' values between 564 and 592, never entering the clauses to pop a chord.

So, in the end the generate method is stuck in a infinite loop, always generating: "error in teacher forcing" at index = 1.

Is there any way to get your already trained model?

**Comment by hyeonch** [comment]
there was a mistake while uploading data on github, so we fixed it on #5 and #6 
you can also access the dataset on [DemoPage](https://pozalabs.github.io/ComMU/)
so please retry to preprocess and train with renewed dataset.
and there is a possibility of some errors in teacher forcing with the code we uploaded in June, especially in case the model is not trained well, we are going to renew the code soon.
Thank you.
